############################################################################
# vendor/boss/app/boss1-app/watch-ui/httpd/Makefile
#
# HTTP Server - using Directory.mk for subdirectories:
#   - lib: thttpd library and HTTP server API
#   - content: HTML files and ROMFS generation
#   - cgi: CGI programs (BINFS) - separate application
#
############################################################################

MENUDESC = "MY HTTPD"
include $(APPDIR)/Directory.mk
